In [71]:
import numpy as np
import pandas as pd
import sys

sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr0_mat100.csv')
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr0.csv')
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr0.csv')
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte0_mat100.csv')
test0=pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte0_mat100.csv',delimiter=' ')
d2 = pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr2_mat100.csv',delimiter=' ')
d = pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr0_mat100.csv',delimiter=' ')
l= pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr0.csv',delimiter=' ')
labels_train0=l.values

In [49]:
train0=d.values
def gauss(t):
    return(np.exp(-t**2/2))


In [50]:
matrix=np.zeros((1999,1999))
for i in range(1999):
    for j in range(1999):
        matrix[i][j]=gauss(np.linalg.norm(train0[i]-train0[j],2))

In [82]:


y=np.zeros(1999)
for i in range(1999):
    y[i]=int(labels_train0[i+1][0][-1])

In [130]:
i=0.01999*np.eye(1999)

    
alpha0=np.matmul(np.linalg.inv(matrix+i),y)

In [87]:
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte0_mat100.csv')
test0=pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte0_mat100.csv',delimiter=' ')
testdata0=test0.values

In [131]:
results0=np.zeros(999)
for k in range(999):
    x=testdata0[k]
    vectx=np.zeros(1999)
    for j in range(1999):
        vectx[j]=gauss(np.linalg.norm(x-train0[j],2))
    u=np.matmul(vectx,alpha0)
    print(u)
    if u<0.5:
        results0[k]=0
    else:
        results0[k]=1

0.7261076470170451
0.6603610930024502
0.5635688791056737
0.4721162247699908
0.4122050734165441
0.527237908176545
0.26132074381521875
0.5569778220612136
0.3879952458956666
0.61251070246729
0.620846228057502
0.3805370945713378
0.7140119900832929
0.5409913692691362
0.6459320745711921
0.4369872368976928
0.570707939260302
0.4110660456763071
0.4970094203254405
0.6576120334095208
0.4447038654107871
0.5125525011689547
0.7050299916186304
0.3507715118988415
0.5296677697366476
0.4940110749457176
0.5741441128540998
0.3200651320264001
0.3978039945008618
0.3655841623903484
0.6653794921120948
0.424195589680636
0.0435942795731421
0.4332147193210858
0.3541062052440225
0.2295081758331321
0.3979072580482921
0.5571733960301799
0.21273210628910988
0.5507604043764331
0.7288865150500214
0.4404339074684742
0.43535826465569016
0.7822001064801896
0.42407586836122846
0.5337378937001063
0.6612182258785992
0.41953874361021803
0.25833695425069436
0.08875907899505364
0.4483986660303003
0.7293278608554488
1.022418795

In [107]:
results0

array([1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 1.

In [108]:
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr1_mat100.csv')
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr1.csv')

sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte1_mat100.csv')
t1=pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte1_mat100.csv',delimiter=' ')
d1 = pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr1_mat100.csv',delimiter=' ')
l1= pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr1.csv',delimiter=' ')
train1=d1.values
test1=t1.values
labels_train1=l1.values

In [109]:
matrix1=np.zeros((1999,1999))
for i in range(1999):
    for j in range(1999):
        matrix1[i][j]=gauss(np.linalg.norm(train1[i]-train1[j],2))
        

In [110]:
y1=np.zeros(1999)
for i in range(1999):
    y1[i]=int(labels_train1[i+1][0][-1])

In [132]:
i=0.01999*np.eye(1999)

    
alpha1=np.matmul(np.linalg.inv(matrix1+i),y1)

In [133]:
results1=np.zeros(999)
for k in range(999):
    x=test1[k]
    vectx=np.zeros(1999)
    for j in range(1999):
        vectx[j]=gauss(np.linalg.norm(x-train1[j],2))
    u=np.matmul(vectx,alpha1)
    if u<0.5:
        results1[k]=0
    else:
        results1[k]=1

In [113]:
results1

array([1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 0., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 0., 0., 1., 1.

In [114]:
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr2_mat100.csv')
sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr2.csv')

sys.path.append('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte2_mat100.csv')
t2=pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xte2_mat100.csv',delimiter=' ')
d2 = pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Xtr2_mat100.csv',delimiter=' ')
l2= pd.read_csv('C:\\Users\\lucas\\Downloads\\machine-learning-with-kernel-methods-2021\\Ytr2.csv',delimiter=' ')
train2=d2.values
test2=t2.values
labels_train2=l2.values

In [115]:
matrix2=np.zeros((1999,1999))
for i in range(1999):
    for j in range(1999):
        matrix2[i][j]=gauss(np.linalg.norm(train2[i]-train2[j],2))

In [116]:
y2=np.zeros(1999)
for i in range(1999):
    y2[i]=int(labels_train2[i+1][0][-1])

In [134]:
i=0.01999*np.eye(1999)

    
alpha2=np.matmul(np.linalg.inv(matrix2+i),y2)

In [135]:
results2=np.zeros(999)
for k in range(999):
    x=test2[k]
    vectx=np.zeros(1999)
    for j in range(1999):
        vectx[j]=gauss(np.linalg.norm(x-train2[j],2))
    u=np.matmul(vectx,alpha2)
    if u<0.5:
        results2[k]=0
    else:
        results2[k]=1

In [119]:
results2

array([0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0.,
       1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 1.

In [136]:
result=np.concatenate((np.array([0.]),results0,np.array([0.]),results1,np.array([0.]),results2))

In [144]:
result=result.astype(int)
result

array([0, 1, 1, ..., 0, 0, 1])

In [145]:
solution = pd.DataFrame(result)
  
solution.to_csv("prédictions3_lucas_osmani.csv")

In [138]:
test2.shape

(999, 100)

In [149]:
testdata0[1]

array([0.        , 0.        , 0.01086957, 0.        , 0.        ,
       0.02173913, 0.        , 0.        , 0.01086957, 0.01086957,
       0.        , 0.        , 0.        , 0.01086957, 0.02173913,
       0.        , 0.        , 0.0326087 , 0.        , 0.02173913,
       0.02173913, 0.        , 0.01086957, 0.        , 0.01086957,
       0.02173913, 0.01086957, 0.04347826, 0.0326087 , 0.        ,
       0.        , 0.        , 0.01086957, 0.01086957, 0.02173913,
       0.        , 0.04347826, 0.02173913, 0.01086957, 0.0326087 ,
       0.        , 0.01086957, 0.        , 0.02173913, 0.        ,
       0.01086957, 0.        , 0.02173913, 0.01086957, 0.01086957,
       0.01086957, 0.02173913, 0.01086957, 0.        , 0.02173913,
       0.        , 0.01086957, 0.        , 0.01086957, 0.02173913,
       0.        , 0.        , 0.01086957, 0.        , 0.01086957,
       0.        , 0.        , 0.01086957, 0.        , 0.0326087 ,
       0.01086957, 0.01086957, 0.        , 0.01086957, 0.     